version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: mwsi_hris_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/generated/mock-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/generated/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/mwsi_hris_dev
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    # No volumes: use files baked into the image (do not mount node_modules)

volumes:
  db_data:
