# Backend Production Build
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY backend/package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Production Runtime
FROM node:20-alpine

WORKDIR /usr/src/app

COPY backend/package*.json ./
RUN npm ci --only=production

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 5000

CMD ["node", "dist/index.js"]
