name: Deploy to Vercel

on:
  push:
    branches:
      - ft-development   # change to main in future

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies inside the frontend folder
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      # Build inside the frontend folder
      - name: Build project
        run: |
          cd frontend
          npm run build

      # Deploy using Vercel CLI from inside the frontend folder
      - name: Deploy to Vercel
        run: |
          cd frontend
          npm install -g vercel
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          vercel build --prod --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
